### ISSUE TITLE
Suggestion: Trigger events after approve/reject/suspend

### ISSUE THREAD

**Issue by ghost** [mtvs/eloquent-approval#2]
Any way to implement events to be triggered after these actions?

**Comment by mtvs** [comment]
Hi, good suggestion. It was on my list for future developments too. 

`Eloquent` has a `HasEvents` concern and uses an instance of the `Illuminate\Events\Dispatcher`.

**Comment by mtvs** [comment]
Now v1.2 supports approval events. You can checkout the [readme](https://github.com/mtvs/eloquent-approval#approval-events)
