### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by karmendra** [mtvs/eloquent-approval#3]
1. It would be awesome if we need not have to add these additional columns in the current table, instead have one specific table with polymorphic relation, similar to package like owen-it/laravel-auditing or plank/laravel-mediable. (information to created/updated/deleted the model can be temporarily stored in the table as json or serialized object)

2. Another good thing would be to know how created/updated/deleted the model and who approved/rejected it. (Just another thought while i write this, actually we can use owen-it/laravel-auditing for this).

**Comment by mtvs** [comment]
Hello

1. I don't see any reason to take the `status` column out of the model's table. Here we don't have a `hasMany` relation like the package you mentioned.

2. I don't want to add auditing to this package but it's possible for users to handle it themselves by leveraging model events or using third party packages like you said. In next versions I will add two general events before and after setting a new status that can facilitate this.
